### ISSUE TITLE
Is iOS 13.4 min target correct? Can it be lower?

### ISSUE THREAD

**Issue by danielchiritavivy** [bioche/RealmBinaries#1]
I see `platforms: [.iOS("13.4")]`. I was wondering if that's a requirement or you just chose it like that.

**Comment by kristofkalai** [comment]
It seems to me that it's solved: https://github.com/bioche/RealmBinaries/commit/55f7b35817b618b6e56d0c43a1972f61567fdd40

**Comment by bioche** [comment]
Solved with https://github.com/bioche/RealmBinaries/releases/tag/10.29.0
